add padding to .entry-title and .entry-meta on mobile
WordPress/gutenberg-starter-theme pull request #37
Opened 2018-02-15 21:48 UTC by purzlbaum

2018-02-16 05:51 UTC, ntwb requested changes
Thanks @purzlbaum, please see review comments

2018-02-16 05:51 UTC, ntwb commented on css/blocks.css
> +
Please remove the whitespace added on this line

2018-02-16 05:51 UTC, ntwb commented on css/blocks.css
> +}
Please add back the blank end-of-file line

2018-02-16 08:24 UTC, purzlbaum commented
I removed the blank on end-of-line: https://github.com/WordPress/gutenberg-starter-theme/pull/37/commits

2018-02-16 09:48 UTC, ntwb approved these changes

2018-03-06 14:47 UTC, karmatosed commented
Can you please review the new CSS changes and send a new PR in.

2018-03-29 14:35 UTC, karmatosed commented
@purzlbaum looking at this there are conflicts with blocks.css can you address these please?

2018-04-24 13:25 UTC, closed without merging

2018-04-24 13:26 UTC, purzlbaum commented
@karmatosed looks like someone came up with the .class * solution. I've closed my PR.