Suggested styles
WordPress/gutenberg-starter-theme pull request #7
Opened 2017-08-08 11:56 UTC by AaronRutley

I've suggested some styles to improve the 'gutenberg-demo' post.

2017-08-16 00:11 UTC, ntwb approved these changes
LGTM

2017-08-16 06:18 UTC, tyrann0us reviewed
Nit: Missing whitespace.

2017-08-16 06:18 UTC, tyrann0us commented on style.css
> +	margin:0 auto;
Nit: Missing whitespace between property and value?

2017-08-16 06:18 UTC, tyrann0us commented on blocks.css
> +	margin:0 auto;
Nit: Missing whitespace between property and value?

2017-08-16 06:23 UTC, ntwb commented on blocks.css
> +	margin:0 auto;
Ha, I missed that 😏

2017-08-18 15:39 UTC, melchoyce commented on blocks.css
> +	margin:0 auto;
More indentation here than in the rest of the stylesheet — maybe swap out to match the rest of the stylesheet?

2017-08-18 15:40 UTC, melchoyce commented on blocks.css
> +	text-align: center;
More indentation here than in the rest of the stylesheet — maybe swap out to match the rest of the stylesheet?

2017-08-18 15:40 UTC, melchoyce commented on style.css
> +	margin:0 auto;
Needs a space between `margin` and `0`

2017-08-18 15:40 UTC, melchoyce commented on blocks.css
> +.wp-block-text-columns.alignfull{
Needs a space between `.alignfull` and `{`

2017-08-18 15:44 UTC, melchoyce requested changes
Some minor spacing issues, but otherwise looking good — if you patch those up, and fix up the button width, I think it'll be good to go.

2017-08-18 15:44 UTC, melchoyce commented on blocks.css
> +	margin:0 auto;
Looking at the demo, I don't think this should be full-width.

2017-12-24 13:08 UTC, karmatosed commented
Can you redo this PR with the suggestions in place please @AaronRutley? Note, there have been updates to the theme so make sure you grab the latest and resolve conflicts. Thanks!

2018-01-16 18:44 UTC, karmatosed commented
Closing as we have conflicts and have split this from the .org site now.

2018-01-16 18:44 UTC, closed without merging